### PR TITLE
Typechecked and more thorough README

### PR DESCRIPTION
**Pull request by dialelo**

### CODE REVIEW

**Comment by dialelo** [comment]
@raulraja take a look, addresses some of your points in #38. I'm not a big fan of putting al the docs in the README but I think showing what the library can do is enough, users that want more information will go to the more thorough documentation site.

Do you think a table of contents is needed?

**Comment by dialelo** [comment]
Forgot to mention, see [the end result](https://github.com/47deg/fetch/blob/better-readme/README.md)

**Comment by raulraja** [comment]
Looks great and no table of contents is needed. I think this covers those user that may run into the lib without a specific need but are curious to see what it does. If there is new stuff we may want to have Maureen do a quick Lang pass. LGTM!

**Comment by dialelo** [comment]
No new stuff yet except for the change in fetch's signature, going to release 0.2.0 with this and the new syntax you contributed! :shipit:

**Pull request merged**
