### PR TITLE
Fetch#liftIO

### LINKED ISSUE #181: Support for lifting IO actions without related Data/DataSource into Fetch
This is something that Omer Zach brought up in the Gitter channel, and we'd need to do some modifications to Fetch in order to support it. The idea is that, if you have an `IO[A]` or `IO[Option[A]]` that represents a Fetch but can't be batched, you should be able to lift it to Fetch. These IO actions wouldn't be batched or cached, so they execute every time a Fetch is run regardless of the contents of the cache.

```scala
def getUser: IO[User] = ???
def maybeGetUser: IO[Option[User]] = ???

def fetchUser[F[_] : ConcurrentEffect] : Fetch[F, User] = Fetch.liftIO(getUser)
def maybeFetchUser[F[_] : ConcurrentEffect] : Fetch[F, Option[User]] = Fetch.liftIO(maybeGetUser)
```

As a "side-effect", we'd be able to embed arbitrary IO actions in a Fetch, even those that perform writes/logging/debugging or anything else.

### PR DESCRIPTION
**Pull request by purrgrammer**
Closes #181

### CODE REVIEW

**Comment by omerzach** [comment]
Anything I can do to help get this merged? We'd like to use it as soon as it's ready.

**Comment by raulraja** [comment]
@omerzach This is now in master. @purrgrammer can we do a minor release or is there something else we need to wait for?

**Comment by omerzach** [comment]
Thank you!

**Comment by purrgrammer** [comment]
Should be available in 1.0.1-SNAPSHOT @omerzach

**Pull request merged**
