### PR TITLE
Update to scala 2.13 (Issue #216)

### PR DESCRIPTION
**Pull request by bijancn**
I made some small progress towards https://github.com/47deg/fetch/issues/216 but from some of your custom plugins this dependency is coming from that can't be resolved for 2.13
```
org.spire-math:kind-projector_2.13:0.9.9
```
I fixed it in the sbt file of the project but it's still there. Do you think you can upgrade your base library first or can we remove this dependency? @purrgrammer 

PS: Sorry for the reformatting, I have `scalafmt` on by default.

### CODE REVIEW

**Comment by juanpedromoreno** [comment]
Thanks @bijancn for your time.

If you rebase against master, I've just merged https://github.com/47deg/fetch/pull/218, which should fix the `kind-projector` issue.

**Comment by bijancn** [comment]
So I think I got everything working :)

**Comment by purrgrammer** [comment]
Thanks a lot @bijancn :heart:

**Comment by purrgrammer** [comment]
@bijancn just a comment: your commits don't have your email associated so Github doesn't link them to your account. If that's ok with you I can merge it right away.

**Comment by bijancn** [comment]
Let me fix that :)

**Comment by bijancn** [comment]
Damnit. That is somehow harder than the fix itself... I'll create a new PR I think

**Comment by bijancn** [comment]
Okay I think I managed to migrate the changes over with the correct email :) https://github.com/47deg/fetch/pull/219

**Pull request closed without merging**
