### PR TITLE
1.2.1 release

### PR DESCRIPTION
**Pull request by purrgrammer**

### CODE REVIEW

**Comment by jtjeferreira** [comment]
I dont see the 1.2.1 in releases page nor in maven central. Any problem?

**Comment by calvellido** [comment]
@jtjeferreira yes, it seems that basically [this](https://github.com/47deg/fetch/pull/229) and [this](https://github.com/47deg/fetch/pull/230) 🤒

**Comment by jtjeferreira** [comment]
> @jtjeferreira yes, it seems that basically #229 and #230 are preventing the new release to happen face_with_thermometer

maybe disable the coverage temporarily for scala 2.13?

**Comment by purrgrammer** [comment]
Should be out now, sorry for the hiccup!

**Pull request merged**
